fastlane_version "2.40.0"

default_platform :ios

platform :ios do
  #
  # Learn more here: https://docs.fastlane.tools/getting-started/ios/beta-deployment/
  #             and: https://docs.fastlane.tools/getting-started/android/beta-deployment/
  #
  lane :beta do |values|
    # Fabric generated this lane for deployment to Crashlytics Beta

    register_devices(devices_file: "devices.txt")
    # match(force_for_new_devices: true, type: "adhoc")

    # increment_build_number(xcodeproj: "onoma.xcodeproj")

    # set 'export_method' to 'ad-hoc' if your Crashlytics Beta distribution uses ad-hoc provisioning
    gym(scheme: 'onoma', export_method: 'development')


    emails = values[:test_email] ? values[:test_email] : ['by-lout-chi@hotmail.fr', 'bonjour@ono.ma'] # You can list more emails here
    groups = values[:test_email] ? nil : nil # You can define groups on the web and reference them here

    crashlytics(api_token: '66f956370ab04f9ad032c76dcd9453c2ab8145c3',
             build_secret: '25356f4dd3e5b9e04089b926690a709ac8240e40b194217f33fbad2720ea84c2',
                   emails: emails,
                   groups: groups,
                    notes: 'Distributed with fastlane', # Check out the changelog_from_git_commits action
            notifications: true) # Should this distribution notify your testers via email?

    # for all available options run `fastlane action crashlytics`

    # You can notify your team in chat that a beta build has been uploaded
    slack(
       slack_url: "https://hooks.slack.com/services/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",
       channel: "general",
       message: "Successfully uploaded a beta release - see it at https://fabric.io/_/beta"
    )
  end
end
